import { Question } from '../types';

export const STAGES_METADATA = [
  {
    stage: 1,
    title: 'Meu momento atual',
    subtitle: 'Contexto profissional, nível de clareza e expectativas',
    estimatedMinutes: 2,
  },
  {
    stage: 2,
    title: 'O que me motiva',
    subtitle: 'Importância declarada versus satisfação real em 10 dimensões de energia',
    estimatedMinutes: 3,
  },
  {
    stage: 3,
    title: 'Meus valores e limites',
    subtitle: 'Dilemas e trade-offs do trabalho sem falsas dicotomias',
    estimatedMinutes: 3,
  },
  {
    stage: 4,
    title: 'Como eu trabalho',
    subtitle: 'Padrões de foco, tomada de decisão, comunicação e colaboração',
    estimatedMinutes: 3,
  },
  {
    stage: 5,
    title: 'Meus recursos e oportunidades',
    subtitle: 'Competências reconhecidas, fricções atuais e apoios disponíveis',
    estimatedMinutes: 2,
  },
  {
    stage: 6,
    title: 'Minha próxima fase',
    subtitle: 'Prioridades, tempo disponível e preparação para o plano de 30 dias',
    estimatedMinutes: 2,
  },
];

export const ASSESSMENT_QUESTIONS: Question[] = [
  // =========================================================================
  // ETAPA 1: MEU MOMENTO ATUAL (6 perguntas)
  // =========================================================================
  {
    id: 'e1_q1_fase',
    stage: 1,
    order: 1,
    title: 'Como você descreve seu momento profissional hoje?',
    instruction: 'Selecione a opção que melhor retrata o seu momento presente.',
    type: 'single_choice',
    required: true,
    dimensionsRelated: ['desenvolvimentoFuturo'],
    options: [
      {
        value: 'consolidacao',
        label: 'Consolidação e aprofundamento',
        description: 'Estou seguro no que faço e busco ganhar mais maturidade, consistência e impacto.',
      },
      {
        value: 'transicao',
        label: 'Transição ou reposicionamento',
        description: 'Planejo uma mudança de área, escopo, empresa ou forma de atuar.',
      },
      {
        value: 'reavaliacao',
        label: 'Reavaliação de prioridades e sentido',
        description: 'Questionando o ritmo atual, buscando mais equilíbrio ou reencontrando motivação.',
      },
      {
        value: 'crescimento_acelerado',
        label: 'Expansão e novos desafios',
        description: 'Assumindo mais responsabilidade, liderança ou projetos de maior complexidade.',
      },
      {
        value: 'reestruturacao',
        label: 'Em busca de clareza de direção',
        description: 'Sinto incerteza sobre qual caminho seguir ou qual decisão tomar agora.',
      },
    ],
  },
  {
    id: 'e1_q2_clareza',
    stage: 1,
    order: 2,
    title: 'Quanto você sente clareza sobre suas prioridades profissionais para os próximos 6 a 12 meses?',
    instruction: 'Em uma escala de 1 a 5, onde 1 é muito difuso e 5 é muito nítido.',
    type: 'likert_5',
    required: true,
    dimensionsRelated: ['desenvolvimentoFuturo'],
    leftAnchor: '1 — Quase nenhuma clareza',
    rightAnchor: '5 — Totalmente nítido',
  },
  {
    id: 'e1_q3_satisfacao_geral',
    stage: 1,
    order: 3,
    title: 'Qual é o seu nível geral de satisfação com a sua rotina e experiência de trabalho atual?',
    instruction: 'Considere o equilíbrio entre esforço, aprendizado e realização.',
    type: 'likert_5',
    required: true,
    dimensionsRelated: ['motivacaoEnergia'],
    leftAnchor: '1 — Muito insatisfeito',
    rightAnchor: '5 — Muito realizado',
  },
  {
    id: 'e1_q4_energia_ocupada',
    stage: 1,
    order: 4,
    title: 'O que mais consome sua atenção e energia no dia a dia?',
    instruction: 'Selecione até 2 aspectos principais.',
    type: 'multi_choice',
    maxSelections: 2,
    required: true,
    dimensionsRelated: ['ambienteTrabalho', 'valoresLimites'],
    options: [
      { value: 'sobrecarga_operacional', label: 'Sobrecarga de tarefas operacionais e urgências' },
      { value: 'alinhamento_comunicacao', label: 'Alinhamento com pessoas, reuniões e comunicação frequente' },
      { value: 'tomada_decisao', label: 'Responsabilidade por decisões difíceis sob pressão' },
      { value: 'falta_clareza', label: 'Ambiguidade de expectativas e metas pouco claras' },
      { value: 'aprendizado_novo', label: 'Curva de aprendizado intensa em novos temas ou ferramentas' },
      { value: 'equilibrio_vida', label: 'Dificuldade em desconectar e manter limites pessoais' },
    ],
  },
  {
    id: 'e1_q5_desejo_compreensao',
    stage: 1,
    order: 5,
    title: 'O que você mais gostaria de compreender melhor sobre si no trabalho?',
    instruction: 'Escolha o ponto mais crítico para a sua reflexão.',
    type: 'single_choice',
    required: true,
    dimensionsRelated: ['desenvolvimentoFuturo', 'colaboracaoComunicacao'],
    options: [
      { value: 'motivadores_reais', label: 'O que realmente me energiza versus o que faço por mera inércia' },
      { value: 'estilo_trabalho', label: 'Meu ritmo ideal de produtividade, concentração e autonomia' },
      { value: 'relacionamentos', label: 'Como me posiciono, comunico limites e colaboro com outros' },
      { value: 'proximos_passos', label: 'Como estruturar passos concretos e sustentáveis para evoluir' },
    ],
  },
  {
    id: 'e1_q6_descoberta_util',
    stage: 1,
    order: 6,
    title: 'Em uma frase curta: o que tornaria esta experiência do Mapa Rumo verdadeiramente valiosa para você?',
    instruction: 'Opcional, mas ajuda a calibrar a síntese do seu diagnóstico.',
    type: 'short_text',
    required: false,
    placeholder: 'Ex: Entender por que ando me sentindo drenado(a) mesmo gostando do projeto...',
    dimensionsRelated: ['desenvolvimentoFuturo'],
  },

  // =========================================================================
  // ETAPA 2: O QUE ME MOTIVA (10 perguntas com medição pareada: Importância vs Satisfação)
  // =========================================================================
  {
    id: 'e2_m1_autonomia',
    stage: 2,
    order: 7,
    title: 'Autonomia e liberdade de condução',
    instruction: 'Avalie a importância desta dimensão para você e o seu nível de satisfação atual.',
    type: 'importance_satisfaction',
    required: true,
    dimensionsRelated: ['motivacaoEnergia', 'ambienteTrabalho'],
  },
  {
    id: 'e2_m2_aprendizado',
    stage: 2,
    order: 8,
    title: 'Aprendizado contínuo e desenvolvimento intelectual',
    instruction: 'Estar diante de temas que desafiam seu intelecto e expandem seu repertório.',
    type: 'importance_satisfaction',
    required: true,
    dimensionsRelated: ['motivacaoEnergia', 'desenvolvimentoFuturo'],
  },
  {
    id: 'e2_m3_resolucao_problemas',
    stage: 2,
    order: 9,
    title: 'Resolução de problemas complexos e desafios práticos',
    instruction: 'Encontrar soluções elegantes para nós difíceis ou processos ineficientes.',
    type: 'importance_satisfaction',
    required: true,
    dimensionsRelated: ['motivacaoEnergia'],
  },
  {
    id: 'e2_m4_criatividade',
    stage: 2,
    order: 10,
    title: 'Criatividade, criação autoral e experimentação',
    instruction: 'Ter margem para propor ideias próprias, testar abordagens novas e dar sua assinatura.',
    type: 'importance_satisfaction',
    required: true,
    dimensionsRelated: ['motivacaoEnergia'],
  },
  {
    id: 'e2_m5_impacto',
    stage: 2,
    order: 11,
    title: 'Sentido de utilidade e impacto concreto no que faz',
    instruction: 'Saber com clareza quem se beneficia do seu trabalho e enxergar resultados tangíveis.',
    type: 'importance_satisfaction',
    required: true,
    dimensionsRelated: ['motivacaoEnergia', 'valoresLimites'],
  },
  {
    id: 'e2_m6_colaboracao',
    stage: 2,
    order: 12,
    title: 'Colaboração próxima e trocas humanas ricas',
    instruction: 'Trabalhar em parceria, compartilhar vitórias e aprender com pares de confiança.',
    type: 'importance_satisfaction',
    required: true,
    dimensionsRelated: ['colaboracaoComunicacao'],
  },
  {
    id: 'e2_m7_estabilidade',
    stage: 2,
    order: 13,
    title: 'Estabilidade, previsibilidade e segurança de contexto',
    instruction: 'Ter clareza das regras do jogo, horizonte financeiro e processos organizados.',
    type: 'importance_satisfaction',
    required: true,
    dimensionsRelated: ['ambienteTrabalho', 'valoresLimites'],
  },
  {
    id: 'e2_m8_reconhecimento',
    stage: 2,
    order: 14,
    title: 'Reconhecimento explícito, valorização e prestígio',
    instruction: 'Sentir que sua entrega é vista, valorizada e compensada adequadamente.',
    type: 'importance_satisfaction',
    required: true,
    dimensionsRelated: ['motivacaoEnergia'],
  },
  {
    id: 'e2_m9_variedade',
    stage: 2,
    order: 15,
    title: 'Variedade e dinamismo no dia a dia',
    instruction: 'Mudar de contexto, interagir com frentes diferentes e evitar monotonia.',
    type: 'importance_satisfaction',
    required: true,
    dimensionsRelated: ['ambienteTrabalho'],
  },
  {
    id: 'e2_m10_profundidade',
    stage: 2,
    order: 16,
    title: 'Foco profundo e ritmo sustentável de imersão',
    instruction: 'Tempo protegido para pensar com calma e produzir com alto rigor sem interrupções constantes.',
    type: 'importance_satisfaction',
    required: true,
    dimensionsRelated: ['ambienteTrabalho', 'valoresLimites'],
  },

  // =========================================================================
  // ETAPA 3: MEUS VALORES E LIMITES (8 tensões situacionais)
  // =========================================================================
  {
    id: 'e3_t1_autonomia_orientacao',
    stage: 3,
    order: 17,
    title: 'Autonomia vs Orientação Detalhada',
    instruction: 'Onde você se sente mais produtivo(a) e confortável?',
    type: 'tension_slider',
    required: true,
    dimensionsRelated: ['ambienteTrabalho', 'valoresLimites'],
    leftAnchor: 'Prefiro liberdade total para decidir o método, mesmo com mais ambiguidade',
    rightAnchor: 'Prefiro alinhamento detalhado e expectativas explícitas antes de iniciar',
  },
  {
    id: 'e3_t2_seguranca_experimentacao',
    stage: 3,
    order: 18,
    title: 'Previsibilidade vs Experimentação',
    instruction: 'Em relação ao ambiente e às apostas do dia a dia:',
    type: 'tension_slider',
    required: true,
    dimensionsRelated: ['valoresLimites'],
    leftAnchor: 'Valorizo estabilidade, consistência e processos consolidados',
    rightAnchor: 'Valorizo ambientes dinâmicos, que testam hipóteses mesmo com risco de erro',
  },
  {
    id: 'e3_t3_visibilidade_tranquilidade',
    stage: 3,
    order: 19,
    title: 'Visibilidade vs Discrição Operacional',
    instruction: 'Em relação à exposição do seu trabalho:',
    type: 'tension_slider',
    required: true,
    dimensionsRelated: ['colaboracaoComunicacao', 'motivacaoEnergia'],
    leftAnchor: 'Gosto de estar na linha de frente, apresentando e defendendo projetos',
    rightAnchor: 'Prefiro atuar nos bastidores com tranquilidade, sem depender de holofotes',
  },
  {
    id: 'e3_t4_especializacao_generalismo',
    stage: 3,
    order: 20,
    title: 'Profundidade Especialista vs Amplitude Multidisciplinar',
    instruction: 'Sobre o escopo da sua atuação:',
    type: 'tension_slider',
    required: true,
    dimensionsRelated: ['desenvolvimentoFuturo'],
    leftAnchor: 'Quero dominar profundamente um domínio específico com alto rigor técnico',
    rightAnchor: 'Gosto de transitar entre várias áreas, conectando pontos e orquestrando',
  },
  {
    id: 'e3_t5_velocidade_qualidade',
    stage: 3,
    order: 21,
    title: 'Velocidade de Entrega vs Acabamento e Refinamento',
    instruction: 'Quando o prazo pressiona:',
    type: 'tension_slider',
    required: true,
    dimensionsRelated: ['valoresLimites', 'ambienteTrabalho'],
    leftAnchor: 'Prefiro colocar algo no ar rápido para iterar, mesmo imperfeito',
    rightAnchor: 'Prefiro cuidar dos detalhes e garantir qualidade antes de divulgar',
  },
  {
    id: 'e3_t6_ambicao_equilibrio',
    stage: 3,
    order: 22,
    title: 'Aceleração de Carreira vs Proteção de Limites Pessoais',
    instruction: 'Qual balanço faz mais sentido para o seu momento presente?',
    type: 'tension_slider',
    required: true,
    dimensionsRelated: ['valoresLimites'],
    leftAnchor: 'Momento de acelerar forte e priorizar a carreira, mesmo com dedicação extra',
    rightAnchor: 'Momento de proteger saúde, vida pessoal e manter carga sustentável',
  },
  {
    id: 'e3_t7_independencia_colegiado',
    stage: 3,
    order: 23,
    title: 'Execução Solo vs Decisões Colegiadas',
    instruction: 'Sobre a dinâmica de decisão:',
    type: 'tension_slider',
    required: true,
    dimensionsRelated: ['colaboracaoComunicacao'],
    leftAnchor: 'Prefiro ter a palavra final e avançar sozinho sem depender de consensos',
    rightAnchor: 'Prefiro construir consensos e validar decisões junto ao time',
  },
  {
    id: 'e3_t8_estrutura_flexibilidade',
    stage: 3,
    order: 24,
    title: 'Planejamento Rígido vs Adaptação Emergente',
    instruction: 'Como você lida com cronogramas e rotinas:',
    type: 'tension_slider',
    required: true,
    dimensionsRelated: ['ambienteTrabalho'],
    leftAnchor: 'Sinto segurança com planos claros, prazos bem definidos e rotina estável',
    rightAnchor: 'Funciono melhor com flexibilidade para ajustar rumos conforme o contexto pede',
  },

  // =========================================================================
  // ETAPA 4: COMO EU TRABALHO (8 perguntas)
  // =========================================================================
  {
    id: 'e4_q1_organizacao',
    stage: 4,
    order: 25,
    title: 'Como você costuma organizar sua semana de trabalho?',
    instruction: 'Identifique seu padrão prático mais recorrente.',
    type: 'single_choice',
    required: true,
    dimensionsRelated: ['ambienteTrabalho'],
    options: [
      { value: 'metodico', label: 'Blocos de tempo planejados com antecedência e listas priorizadas' },
      { value: 'reativo_priorizado', label: 'Reviso as prioridades no início do dia e ajusto conforme demandas chegam' },
      { value: 'fluxo_emergente', label: 'Trabalho focado no que é mais urgente ou instigante no momento' },
      { value: 'sobrecarregado', label: 'Tenho dificuldade de manter consistência e a sensação de urgência predomina' },
    ],
  },
  {
    id: 'e4_q2_foco',
    stage: 4,
    order: 26,
    title: 'Como funciona sua capacidade de sustentar foco em tarefas profundas?',
    instruction: 'Considere a realidade das suas últimas semanas.',
    type: 'single_choice',
    required: true,
    dimensionsRelated: ['ambienteTrabalho'],
    options: [
      { value: 'foco_consistente', label: 'Consigo entrar em estado de concentração prolongada facilmente' },
      { value: 'foco_com_esforco', label: 'Consigo manter foco, mas interrupções e mensagens fragmentam meu dia' },
      { value: 'foco_sob_pressao', label: 'Costumo engajar com força máxima quando o prazo está próximo' },
      { value: 'dispersao_frequente', label: 'Tenho sentido muita dispersão e cansaço mental recente' },
    ],
  },
  {
    id: 'e4_q3_comunicacao',
    stage: 4,
    order: 27,
    title: 'Qual é o seu canal de comunicação preferido para resolver temas de trabalho?',
    instruction: 'Selecione a forma que melhor favorece sua clareza.',
    type: 'single_choice',
    required: true,
    dimensionsRelated: ['colaboracaoComunicacao'],
    options: [
      { value: 'assincrono_escrito', label: 'Mensagens ou documentos escritos bem estruturados (assíncrono)' },
      { value: 'sincrono_rapido', label: 'Conversas rápidas de 10-15 minutos (vídeo ou presencial)' },
      { value: 'hibrido', label: 'Documento prévio de leitura seguido de debate focado' },
    ],
  },
  {
    id: 'e4_q4_feedback',
    stage: 4,
    order: 28,
    title: 'Como você costuma lidar com feedbacks e críticas sobre seu trabalho?',
    instruction: 'Selecione a descrição mais sincera.',
    type: 'single_choice',
    required: true,
    dimensionsRelated: ['colaboracaoComunicacao', 'desenvolvimentoFuturo'],
    options: [
      { value: 'proativo', label: 'Peço feedback com frequência e uso como combustível direto de melhoria' },
      { value: 'reflexivo', label: 'Acolho bem, mas preciso de tempo para processar antes de responder' },
      { value: 'sensivel', label: 'Fico reflexivo(a) e às vezes levo para o lado pessoal antes de racionalizar' },
      { value: 'cauteloso', label: 'Sinto falta de feedbacks mais claros e estruturados no meu contexto atual' },
    ],
  },
  {
    id: 'e4_q5_tomada_decisao',
    stage: 4,
    order: 29,
    title: 'Diante de uma decisão com informações incompletas, você tende a:',
    instruction: 'Selecione sua postura espontânea.',
    type: 'single_choice',
    required: true,
    dimensionsRelated: ['ambienteTrabalho'],
    options: [
      { value: 'analitico', label: 'Investigar mais dados até reduzir ao máximo a incerteza' },
      { value: 'pragmatico', label: 'Decidir com o que tem em mãos e ajustar no caminho' },
      { value: 'consultivo', label: 'Ouvir pares experientes antes de fechar a posição' },
      { value: 'intuitivo', label: 'Confiar na intuição prática e em experiências passadas análogas' },
    ],
  },
  {
    id: 'e4_q6_mudancas',
    stage: 4,
    order: 30,
    title: 'Quando o contexto ou a estratégia mudam repentinamente no meio do caminho:',
    instruction: 'Como seu sistema reage?',
    type: 'single_choice',
    required: true,
    dimensionsRelated: ['ambienteTrabalho', 'valoresLimites'],
    options: [
      { value: 'adaptativo_rapido', label: 'Pivotar rápido me entusiasma; vejo oportunidade de renovar' },
      { value: 'pragmatico_calmo', label: 'Aceito pragmaticamente, mas exijo clareza nos novos critérios' },
      { value: 'desgaste_inicial', label: 'Sinto frustração inicial pelo esforço perdido, depois me adapto' },
      { value: 'resistencia', label: 'Me desgasto bastante; prefiro compromissos consistentes até o final' },
    ],
  },
  {
    id: 'e4_q7_posicionamento',
    stage: 4,
    order: 31,
    title: 'Em reuniões e conversas estratégicas, você costuma:',
    instruction: 'Selecione o padrão mais comum.',
    type: 'single_choice',
    required: true,
    dimensionsRelated: ['colaboracaoComunicacao'],
    options: [
      { value: 'voz_ativa', label: 'Colocar meu ponto de vista com firmeza e liderar a discussão' },
      { value: 'observador_cirurgico', label: 'Ouvir com atenção e intervir pontualmente com perguntas-chave' },
      { value: 'facilitador', label: 'Ajudar a sintetizar o que os outros dizem e destravar impasses' },
      { value: 'discreto', label: 'Prefiro manifestar minha opinião por escrito após a conversa' },
    ],
  },
  {
    id: 'e4_q8_limites_nao',
    stage: 4,
    order: 32,
    title: 'Qual é o seu grau de facilidade para dizer "não" ou negociar prazos irreais?',
    instruction: 'Em uma escala de 1 a 5, onde 1 é muito difícil e 5 é muito natural.',
    type: 'likert_5',
    required: true,
    dimensionsRelated: ['valoresLimites', 'colaboracaoComunicacao'],
    leftAnchor: '1 — Muito difícil (costumo absorver sobrecarga)',
    rightAnchor: '5 — Totalmente seguro(a) e transparente',
  },

  // =========================================================================
  // ETAPA 5: MEUS RECURSOS E OPORTUNIDADES (8 perguntas)
  // =========================================================================
  {
    id: 'e5_q1_fortalezas_reconhecidas',
    stage: 5,
    order: 33,
    title: 'Quais competências e qualidades você reconhece com clareza em si?',
    instruction: 'Selecione até 3 fortalezas que você entrega de forma consistente.',
    type: 'multi_choice',
    maxSelections: 3,
    required: true,
    dimensionsRelated: ['desenvolvimentoFuturo', 'motivacaoEnergia'],
    options: [
      { value: 'clareza_estruturacao', label: 'Capacidade de organizar ideias confusas e dar estrutura lógica' },
      { value: 'resolucao_pratica', label: 'Pragmatismo para destravar problemas e executar com eficiência' },
      { value: 'visao_estrategica', label: 'Pensamento sistêmico e capacidade de enxergar o panorama amplo' },
      { value: 'empatia_escuta', label: 'Sensibilidade para relações humanas, escuta ativa e mediação' },
      { value: 'rigor_qualidade', label: 'Atenção ao acabamento, precisão técnica e critérios de qualidade' },
      { value: 'comunicacao_didatica', label: 'Clareza para explicar conceitos difíceis e engajar outras pessoas' },
      { value: 'resiliencia_consistencia', label: 'Capacidade de sustentar o ritmo e manter o foco a longo prazo' },
    ],
  },
  {
    id: 'e5_q2_confianca_plena',
    stage: 5,
    order: 34,
    title: 'Em quais momentos ou tarefas você sente que está no seu melhor?',
    instruction: 'Selecione o cenário em que sua confiança flui com mais naturalidade.',
    type: 'single_choice',
    required: true,
    dimensionsRelated: ['motivacaoEnergia'],
    options: [
      { value: 'criacao_zero', label: 'Ao conceber algo do zero e desenhar a solução' },
      { value: 'otimizacao', label: 'Ao pegar algo imperfeito e transformar em um processo impecável' },
      { value: 'mentoria_time', label: 'Ao apoiar e desenvolver colegas, destravando o time' },
      { value: 'articulacao', label: 'Ao negociar alinhamentos estratégicos com lideranças e clientes' },
      { value: 'execucao_profunda', label: 'Ao produzir uma entrega densa com foco exclusivo e sem ruído' },
    ],
  },
  {
    id: 'e5_q3_situacoes_desafiadoras',
    stage: 5,
    order: 35,
    title: 'Quais situações no trabalho mais costumam drenar sua energia ou gerar insegurança?',
    instruction: 'Selecione até 2 situações mais comuns.',
    type: 'multi_choice',
    maxSelections: 2,
    required: true,
    dimensionsRelated: ['valoresLimites', 'ambienteTrabalho'],
    options: [
      { value: 'conflitos_politicos', label: 'Tensões políticas, disputas de território ou falta de transparência' },
      { value: 'reunioes_improdutivas', label: 'Excesso de reuniões longas sem decisões objetivas' },
      { value: 'microgerenciamento', label: 'Supervisão excessiva ou falta de confiança no meu discernimento' },
      { value: 'isolamento', label: 'Falta de interlocutores para trocar ideias e validar hipóteses' },
      { value: 'alta_ambiguidade', label: 'Ausência total de direcionamento ou critérios de sucesso' },
    ],
  },
  {
    id: 'e5_q4_competencias_praticar',
    stage: 5,
    order: 36,
    title: 'Qual competência você gostaria de exercitar de forma mais consciente no seu dia a dia?',
    instruction: 'Escolha a principal para este próximo ciclo.',
    type: 'single_choice',
    required: true,
    dimensionsRelated: ['desenvolvimentoFuturo'],
    options: [
      { value: 'postura_limites', label: 'Comunicação assertiva e sustentação de limites saudáveis' },
      { value: 'delegacao', label: 'Delegação e compartilhamento de responsabilidades' },
      { value: 'priorizacao_estrategica', label: 'Capacidade de priorizar o essencial e desapegar do secundário' },
      { value: 'posicionamento_influencia', label: 'Presença profissional e influência em conversas estratégicas' },
      { value: 'gestao_emocional', label: 'Gestão de ansiedade diante de incertezas e cobranças' },
    ],
  },
  {
    id: 'e5_q5_apoios_disponiveis',
    stage: 5,
    order: 37,
    title: 'Quais recursos ou apoios você sente que tem à disposição hoje?',
    instruction: 'Selecione todos os que se aplicam.',
    type: 'multi_choice',
    required: true,
    dimensionsRelated: ['desenvolvimentoFuturo', 'colaboracaoComunicacao'],
    options: [
      { value: 'pares_confianca', label: 'Colegas de trabalho de confiança com quem posso conversar com franqueza' },
      { value: 'lideranca_aberta', label: 'Liderança acessível que apoia meu desenvolvimento' },
      { value: 'espaco_autonomia', label: 'Margem prática para propor mudanças na minha rotina' },
      { value: 'rede_externa', label: 'Rede externa de mentores, amigos ou profissionais da área' },
      { value: 'recursos_estudo', label: 'Acesso a livros, cursos ou materiais de estudo' },
      { value: 'apoio_limitado', label: 'Sinto que estou com apoios escassos e atuando de forma isolada' },
    ],
  },
  {
    id: 'e5_q6_obstaculo_principal',
    stage: 5,
    order: 38,
    title: 'Qual é o maior obstáculo percebido para implementar melhorias na sua rotina profissional?',
    instruction: 'Selecione o fator mais limitante.',
    type: 'single_choice',
    required: true,
    dimensionsRelated: ['ambienteTrabalho', 'valoresLimites'],
    options: [
      { value: 'tempo_sobrecarga', label: 'Falta de tempo e sobrecarga de demandas urgentes' },
      { value: 'cultura_ambiente', label: 'Cultura do ambiente (pressão constante, pouca flexibilidade)' },
      { value: 'clareza_prioridade', label: 'Dificuldade própria em escolher uma direção e manter a disciplina' },
      { value: 'medo_desagradar', label: 'Receio de desapontar expectativas alheias ou parecer descompromissado(a)' },
      { value: 'energia_baixa', label: 'Cansaço acumulado ao final do dia' },
    ],
  },
  {
    id: 'e5_q7_percepcao_progresso',
    stage: 5,
    order: 39,
    title: 'Olhando para os últimos 12 meses, você sente que sua trajetória profissional esteve:',
    instruction: 'Considere aprendizado e evolução pessoal.',
    type: 'single_choice',
    required: true,
    dimensionsRelated: ['desenvolvimentoFuturo'],
    options: [
      { value: 'avanco_claro', label: 'Em evolução consistente e perceptível' },
      { value: 'estabilidade_confortavel', label: 'Em um platô estável, mas confortável' },
      { value: 'estagnacao_incomoda', label: 'Em um platô que começou a gerar desconforto e desmotivação' },
      { value: 'turbulencia', label: 'Em um período de instabilidade ou redefinição forçada' },
    ],
  },
  {
    id: 'e5_q8_potencial_latente',
    stage: 5,
    order: 40,
    title: 'Existe alguma habilidade sua que você sente que está subutilizada no trabalho atual?',
    instruction: 'Selecione a que mais se destaca.',
    type: 'single_choice',
    required: true,
    dimensionsRelated: ['motivacaoEnergia', 'desenvolvimentoFuturo'],
    options: [
      { value: 'criatividade_autoral', label: 'Minha criatividade e capacidade de inventar novas abordagens' },
      { value: 'pensamento_estrategico', label: 'Minha visão de longo prazo e pensamento estratégico' },
      { value: 'desenvolvimento_pessoas', label: 'Minha habilidade em orientar, ensinar e desenvolver outras pessoas' },
      { value: 'comunicacao_articulacao', label: 'Minha comunicação persuasiva e expressão oral/escrita' },
      { value: 'bem_aproveitada', label: 'Sinto que minhas principais habilidades estão bem aproveitadas' },
    ],
  },

  // =========================================================================
  // ETAPA 6: MINHA PRÓXIMA FASE & PLANO DE 30 DIAS (8 perguntas)
  // =========================================================================
  {
    id: 'e6_q1_experimentar_mais',
    stage: 6,
    order: 41,
    title: 'O que você gostaria de experimentar com mais intencionalidade nas próximas semanas?',
    instruction: 'Selecione a frente que traria maior benefício.',
    type: 'single_choice',
    required: true,
    dimensionsRelated: ['desenvolvimentoFuturo'],
    options: [
      { value: 'blocos_foco', label: 'Proteger blocos semanais inegociáveis para trabalho profundo' },
      { value: 'conversas_alinhamento', label: 'Ter conversas francas de alinhamento de expectativas com líderes ou pares' },
      { value: 'projetos_autorais', label: 'Dedicar 10% do tempo a uma iniciativa ou estudo que desperte genuína curiosidade' },
      { value: 'desaceleracao_pausas', label: 'Estabelecer pausas deliberadas e horários firmes para encerrar o expediente' },
      { value: 'registro_aprendizados', label: 'Criar o hábito de registrar aprendizados e vitórias da semana' },
    ],
  },
  {
    id: 'e6_q2_reduzir_reorganizar',
    stage: 6,
    order: 42,
    title: 'O que você mais precisa reduzir ou reorganizar para abrir espaço mental?',
    instruction: 'Selecione a principal fonte de ruído.',
    type: 'single_choice',
    required: true,
    dimensionsRelated: ['valoresLimites', 'ambienteTrabalho'],
    options: [
      { value: 'reunioes_dispensaveis', label: 'Participação em reuniões das quais não preciso fazer parte ativa' },
      { value: 'perfeccionismo', label: 'Polimento excessivo em tarefas que só exigem nível bom o suficiente' },
      { value: 'disponibilidade_imediata', label: 'A necessidade de responder instantaneamente a qualquer notificação' },
      { value: 'assumir_tudo', label: 'Aceitar pedidos extras sem checar minha capacidade real de entrega' },
    ],
  },
  {
    id: 'e6_q3_preservar_inegociavel',
    stage: 6,
    order: 43,
    title: 'O que você faz questão absoluta de preservar na sua rotina, independentemente das demandas?',
    instruction: 'Selecione o seu principal valor inegociável.',
    type: 'single_choice',
    required: true,
    dimensionsRelated: ['valoresLimites'],
    options: [
      { value: 'saude_sono', label: 'Sono de qualidade, atividade física e saúde' },
      { value: 'familia_relacoes', label: 'Tempo presente com família, parceiro(a) e amigos' },
      { value: 'autonomia_decisao', label: 'Minha autonomia para gerenciar meus horários e métodos' },
      { value: 'etica_rigor', label: 'Integridade ética e orgulho do que entrego' },
    ],
  },
  {
    id: 'e6_q4_micro_mudanca',
    stage: 6,
    order: 44,
    title: 'Qual pequena mudança de comportamento, se praticada por 30 dias, geraria o maior alívio ou clareza?',
    instruction: 'Selecione o experimento mais viável.',
    type: 'single_choice',
    required: true,
    dimensionsRelated: ['desenvolvimentoFuturo', 'ambienteTrabalho'],
    options: [
      { value: 'planejar_vespera', label: 'Definir as 2 prioridades inegociáveis do dia seguinte ao final da tarde anterior' },
      { value: 'pausa_antes_responder', label: 'Dar 10 minutos antes de aceitar uma nova demanda ou marcar reunião' },
      { value: 'checkin_semanal', label: 'Fazer uma revisão de 20 minutos na sexta-feira sobre o que funcionou e o que travou' },
      { value: 'comunicar_limite', label: 'Avisar explicitamente meu time sobre meus horários de foco profundo' },
    ],
  },
  {
    id: 'e6_q5_tempo_semanal',
    stage: 6,
    order: 45,
    title: 'Quanto tempo semanal você realisticamente pode reservar para seu desenvolvimento e reflexão?',
    instruction: 'Seja sincero(a); o plano de 30 dias será calibrado com base nessa resposta.',
    type: 'single_choice',
    required: true,
    dimensionsRelated: ['desenvolvimentoFuturo'],
    options: [
      { value: '30_minutos', label: '30 a 45 minutos por semana (micro-passos rápidos e objetivos)' },
      { value: '1_hora', label: '1 a 2 horas por semana (tempo adequado para observar e experimentar)' },
      { value: '3_horas_mais', label: '3 horas ou mais por semana (espaço para imersão, estudo e planos maiores)' },
    ],
  },
  {
    id: 'e6_q6_prioridade_central',
    stage: 6,
    order: 46,
    title: 'Qual prioridade você quer colocar no coração do seu plano de 30 dias?',
    instruction: 'Esta escolha definirá o foco das ações recomendadas.',
    type: 'single_choice',
    required: true,
    dimensionsRelated: ['desenvolvimentoFuturo'],
    options: [
      { value: 'foco_organizacao', label: 'Organização da rotina, clareza de foco e redução de sobrecarga' },
      { value: 'comunicacao_posicionamento', label: 'Comunicação assertiva, alinhamento de expectativas e limites' },
      { value: 'clareza_carreira', label: 'Definição estratégica de próximos passos e aprendizados de carreira' },
      { value: 'resgate_energia', label: 'Reconexão com o que me motiva e recuperação de sustentabilidade' },
    ],
  },
  {
    id: 'e6_q7_disposicao_experimentar',
    stage: 6,
    order: 47,
    title: 'Em uma escala de 1 a 5, qual é a sua disposição para testar uma abordagem diferente no trabalho esta semana?',
    instruction: 'Mesmo que seja um experimento pequeno de 15 minutos.',
    type: 'likert_5',
    required: true,
    dimensionsRelated: ['desenvolvimentoFuturo'],
    leftAnchor: '1 — Quero apenas refletir por enquanto',
    rightAnchor: '5 — Pronto(a) para colocar em prática amanhã',
  },
  {
    id: 'e6_q8_compromisso_pessoal',
    stage: 6,
    order: 48,
    title: 'Opcional: Que conselho você daria para si mesmo(a) hoje se fosse seu próprio mentor?',
    instruction: 'Um lembrete reflexivo que será integrado ao fechamento do seu relatório.',
    type: 'short_text',
    required: false,
    placeholder: 'Ex: Lembrar que dizer não para o urgente é dizer sim para o que importa...',
    dimensionsRelated: ['valoresLimites', 'desenvolvimentoFuturo'],
  },
];
